# Camunda configuration
camunda:
  bpm:
    admin-user:
      id: admin
      password: abc123
      first-name: Admin
      last-name: Test
    generic-properties:
      properties:
        initializeTelemetry: false
    filter:
      create: All Tasks
# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
# REST-API configuration
rest:
  api:
    base-url: http://localhost:8180